modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="zombie_mods"
version="1.0.0"
displayName="Zombie Mods"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="david, MCreator"

[[dependencies.zombie_mods]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




